Repository lsngmin/gravifox-web, pull requests merged in 2025-05, with the labels that each got.

#40 Refactor: 내비게이션 바 디자인 변경. Product 메뉴 비활성화.
  src/features/navigation/navigation.js
Labels: 🔨 Refactor, 🎨 Html&css

#42 Refactor PageSection 디자인 및 멘트 수정
  src/features/main/pageSection.js
Labels: 🔨 Refactor, 🎨 Html&css

#44 Refactor Feature 컴포넌트 디자인 변경 및 기타 컴포넌트 소변경 적용
  src/features/main/feature.js
  src/features/main/pageSection.js
  src/features/navigation/components/navigationAuthButton.js
Labels: 🔨 Refactor, 🥰 Accessibility, 🎨 Html&css

#47 Refactor main text component
  src/features/main/mainText.js
Labels: 🔨 Refactor, 🎨 Html&css

#51 Feature: Swagger 문서 페이지 생성 및 적용
  public/swagger.html
  public/swagger.json
  src/features/navigation/navigation.js
  src/pages/Docs.js
  src/routes/routes.js
Labels: ✨ Feature

#52 Refactor FreeTrial 초기 랜딩 페이지 구조 개선. 가독성 향상
  public/swagger.html
  public/swagger.json
  src/features/footer/footer.js
  src/features/freeTrial/analyzeProcess.js
  src/features/freeTrial/components/featureCardGrid.js
  src/features/freeTrial/firstStep.js
  src/features/login/api/signInAPI.js
  src/features/navigation/navigation.js
  src/output.css
  src/pages/Docs.js
  src/pages/freeTrial.js
  src/routes/routes.js
  tailwind.config.js
Labels: 🔨 Refactor

#60 style(navigation): 로그인 버튼 클릭 범위 조정 #49
  src/features/navigation/components/navigationAuthButton.js
Labels: 🔨 Refactor

#62 style(favicon): 파비콘 이미지 변경 #48
  public/gravifox.ico
  public/index.html
Labels: 🎨 Html&css

#63 Refactor free trial page
  src/features/freeTrial/analyzeProcess.js
  src/features/freeTrial/components/backGroundOverlay.js
  src/features/freeTrial/components/featureCardGrid.js
  src/features/freeTrial/components/loadingSpinner.js
  src/features/freeTrial/components/resultAnalyze.js
  src/features/freeTrial/components/startAnalyzeButton.js
  src/features/freeTrial/components/titleSection.js
  src/features/freeTrial/components/uploadBox.js
  src/features/freeTrial/firstStepFileUploader.js
  src/features/navigation/navigation.js
  src/output.css
Labels: 🔨 Refactor

#64 기능 개발건 병합
  public/gravifox.ico
  public/index.html
  src/features/navigation/components/navigationAuthButton.js
  src/features/navigation/navigation.js
Labels: 🌏 Deploy

#72 Refactor/71 nav login buttons group
  src/assets/1.jpg
  src/assets/arrow-right-from-bracket-svgrepo-com.svg
  src/assets/cloud-check-svgrepo-com.svg
  src/assets/house-line-svgrepo-com.svg
  src/assets/image-square-xmark-svgrepo-com.svg
  src/assets/images-user-svgrepo-com.svg
  src/assets/lock-alt-svgrepo-com.svg
  src/features/navigation/components/avatarButton.js
  src/features/navigation/components/navigationAuthButton.js
  src/features/navigation/navigation.js
  src/output.css
Labels: 🔨 Refactor

#74 기능 개발 및 디자인 리팩토링 건 병합
  src/assets/1.jpg
  src/assets/arrow-right-from-bracket-svgrepo-com.svg
  src/assets/cloud-check-svgrepo-com.svg
  src/assets/house-line-svgrepo-com.svg
  src/assets/image-square-xmark-svgrepo-com.svg
  src/assets/images-user-svgrepo-com.svg
  src/assets/lock-alt-svgrepo-com.svg
  src/features/freeTrial/FileUploader.js
  src/features/freeTrial/analyzeProcess.js
  src/features/freeTrial/components/desktopStepper.js
  src/features/freeTrial/components/mobileStepper.js
  src/features/freeTrial/components/uploadBox.js
  src/features/freeTrial/firstStep.js
  src/features/freeTrial/secondStep.js
  src/features/freeTrial/stepper.js
  src/features/freeTrial/thirdStep.js
  src/features/navigation/components/avatarButton.js
  src/features/navigation/components/navigationAuthButton.js
  src/features/navigation/navigation.js
  src/output.css
  src/pages/freeTrial.js
Labels: 🌏 Deploy

#75 Feat/25 profile page
  .env
  .env.production
  src/features/navigation/components/avatarButton.js
  src/features/profile/api/profileAPI.js
  src/features/profile/components/sideBar.js
  src/features/profile/components/sideBarItem.js
  src/features/profile/components/userInfo.js
  src/features/profile/icon/userIcon.js
  src/pages/Profile.js
  src/routes/routes.js
Labels: ✨ Feature
